import matplotlib.pyplot as plt
import seaborn as sns
import torch, os
import pandas as pd
import numpy as np
from .utils import getLogger, restore_dataset_name

logger = getLogger(name = __file__)

length = 20
height = 5

'''
This is the main plotter library.
For all tpp models waiting for being evaluated, you should have two methods implemented.
1. function_prober(data, resolution):
Args:
   1. data: The fresh raw data from the corresponding dataloader. Batch size is 1 and can not be changed.
   2. resolution: It elabrates how many additional time points are inserted between two events. In fact, because
                  new time points are generated by torch.linspace(0, 1, resolution) * time, there are only
                  (resolution - 2) new points.
Output:
   If this model is present in list named 'intensity_available', its function_prober() should have three kinds of outputs.
   1. integral: the values of the intensity integral function at all probing points.
   2. intensity: the values of the intensity function at all probing points.
   3. timestamp: cumulative timestamps of all points that have been used during model distribution estimation.
   Otherwise, it should have two kinds of outputs.
   1. probability: the values of the probability distribution at all probing points.
   2. timestamp: cumulative timestamps of all points that have been used during model distribution estimation.
Function behaviours:
This function should return

2. model_prober
'''

'''
1. We can draw probability distribution plots and intensity function at the same time.
2. We will utilize intensity functions values and their integrals for probability distribution.
   We don't need to implement another model method to obtain them.
'''
intensity_available = ['dwg', 'fullynn', 'ctlstm', 'thp', 'rmtpp']

'''
Intensity function drawing utils
'''
def expand_true_intensity(time, intensity, opt):
    try:
        return true_intensity_dict[restore_dataset_name(opt.dataset_name)](time, intensity, opt.resolution, device = opt.device)
                                                                               # [batch_size, seq_len * resolution]
    except:
        return None

def expand_model_intensity(model, data, opt):
    if opt.model_name in intensity_available:
        return model.function_prober(data, opt.resolution)                     # [batch_size, seq_len * resolution]
    else:
        raise Exception('This model is incompatible with intensity prober!')


def draw_intensity(model, data, desc, plot_count, opt):
    '''
    Now you should investigate your own model implementations and modify this function.
    Because of the design of training_step() and evaluation_step(), intensity and integral outputs can not be handled automatically.

    data: [time_diff, score, target_intensity]
    '''

    _, model_intensity, timestamp = expand_model_intensity(model, data, opt)   # [batch_size, seq_len * resolution]
    time, event, intensity = extract_data(data, opt)                           # [batch_size, seq_len + 1] & [batch_size, seq_len]
    aggregate_time = torch.cumsum(time[:, 1:], dim = -1).squeeze().cpu()       # [batch_size, seq_len]
    true_intensity = expand_true_intensity(time, intensity, opt = opt)         # [batch_size, seq_len * resolution]

    # torch.tensor to numpy.array
    model_intensity = model_intensity.squeeze().detach().cpu().numpy()
    if np.isnan(model_intensity).any():
        '''
        Model intensity prediction has failed!
        '''
        logger.error('We detect NaN in the intensity predictions! Please try again after checking the training log and retraining your model.')
        return 0

    timestamp = timestamp.detach().cpu().numpy().cumsum()
    event = event.squeeze().cpu().numpy()
    if true_intensity is not None:
        true_intensity = true_intensity.squeeze().detach().cpu().numpy()
    
    if true_intensity is not None:
        df = pd.DataFrame.from_dict(
            {'Time': timestamp, 'Predicted Intensity': model_intensity, 'Truth': true_intensity}
        )
    else:
        df = pd.DataFrame.from_dict(
            {'Time': timestamp, 'Predicted Intensity': model_intensity}
        )
    df_intensity_plot = pd.melt(df, 'Time')
    df_intensity_plot.columns = ['Time', '', 'Intensity']
    df_time = pd.DataFrame.from_dict(
            {'Time': aggregate_time, 'Point': np.zeros_like(aggregate_time), 'Event': [f'Event {item}' for item in event]}
    )

    # Draw plot
    fig = plt.figure()
    sns.lineplot(x = 'Time', y = 'Intensity', hue = '', data = df_intensity_plot)
    sns.scatterplot(x = 'Time', y = 'Point', data = df_time, palette = 'pastel', hue = 'Event')
    fig.set_size_inches(length,height)

    if not os.path.exists(os.path.join(opt.store_dir, 'intensity')):
        os.makedirs(os.path.join(opt.store_dir, 'intensity'))
    plt.savefig(os.path.join(opt.store_dir, 'intensity', desc + '_' + str(plot_count) + '.png'), dpi = 1000)
    plt.close(fig = fig)

'''
Probability distribution drawing utils
'''
def expand_true_probability(time, intensity, opt):
    try:
        functions = true_probability_dict[restore_dataset_name(opt.dataset_name)]
    except:
        return None
        
    if len(functions) == 2:
        '''
        Two functions means you should combine the intensity function and correspounding integral function to
        obtain the final probability distribution.
        '''
        expand_true_intensity = \
            functions[0](time, intensity, opt.resolution, device = opt.device) # [batch_size, seq_len * resolution]
        expand_true_integral = \
            functions[1](time, intensity, opt.resolution, device = opt.device) # [batch_size, seq_len * resolution]
        return expand_true_intensity * torch.exp(-expand_true_integral)        # [batch_size, seq_len * resolution]
    else:
        '''
        While for several special tpps defined by probability distributions instead of intensity functions, thing are quite
        easier: go find the distribution and the task is done.
        '''
        expand_true_probability = functions[0](time, intensity, opt.resolution, device = opt.device)
                                                                               # [batch_size, seq_len * resolution]
        return expand_true_probability


probability_available = ['dwg', 'fullynn', 'rmtpp', 'ifl']

def expand_model_probability(opt):
    if opt.model_name not in probability_available:
        raise Exception('This model is incompatible with intensity prober!')

def draw_probability(model, data, desc, plot_count, opt):
    '''
    Now you should investigate your own model implementations and modify this function. If your algorithm is listed in 'intensity_available', its
    model_probe() should return model-learned intensity function values and integral values at all timestamp samples, otherwise model_probe() should output
    the probability distribution values directly(Like several intensity-free models). Thanks to the constant and easy relation from intensity functions
    to correlated probability distributions, we do not require an additional complicated method for probability distribution probe.

    data: [time_diff, score, target_intensity]
    '''
    expand_model_probability(opt)

    if opt.model_name in intensity_available:
        model_intensity_integral, model_intensity, timestamp = expand_model_intensity(model, data, opt)
                                                                               # [batch_size, seq_len * resolution]
        model_probability = model_intensity * torch.exp(-model_intensity_integral)
                                                                               # [batch_size, seq_len * resolution]
    else:
        model_probability, timestamp = \
            model.function_prober(data, opt.resolution)                        # [batch_size, seq_len * resolution]

    time, event, intensity = extract_data(data, opt)                           # [batch_size, seq_len + 1] & [batch_size, seq_len]
    aggregate_time = torch.cumsum(time[:, 1:], dim = -1).cpu().squeeze()       # [batch_size, seq_len]
    true_probability = expand_true_probability(time, intensity, opt)           # [batch_size, seq_len * resolution]

    # torch.tensor to numpy.array
    model_probability = model_probability.squeeze().detach().cpu().numpy()
    if np.isnan(model_probability).any():
        '''
        Model failed the probability prediction!
        '''
        logger.error('We detect NaN in the probability predictions! Please try again after checking the training log and retraining your model.')
        return 0

    timestamp = timestamp.detach().cpu().numpy().cumsum()
    event = event.squeeze().cpu().numpy()
    if true_probability is not None:
        true_probability = true_probability.squeeze().detach().cpu().numpy()
    
    if true_probability is not None:
        df = pd.DataFrame.from_dict(
            {'Time': timestamp, 'Predicted Probability': model_probability, 'Truth': true_probability}
        )
    else:
        df = pd.DataFrame.from_dict(
            {'Time': timestamp, 'Predicted Probability': model_probability}
        )
    df_probability_plot = pd.melt(df, 'Time')
    df_probability_plot.columns = ['Time', '', 'Probability Distribution']
    df_time = pd.DataFrame.from_dict(
            {'Time': aggregate_time, 'Point': np.zeros_like(aggregate_time), 'Event': [f'Event {item}' for item in event]}
    )

    # Draw plot
    fig = plt.figure()
    sns.lineplot(x = 'Time', y = 'Probability Distribution', hue = '', data = df_probability_plot)
    sns.scatterplot(x = 'Time', y = 'Point', data = df_time, palette = 'pastel', hue = 'Event')
    fig.set_size_inches(length,height)

    if not os.path.exists(os.path.join(opt.store_dir, 'probability_distribution')):
        os.makedirs(os.path.join(opt.store_dir, 'probability_distribution'))
    plt.savefig(os.path.join(opt.store_dir, 'probability_distribution', desc + '_' + str(plot_count) + '.png'), dpi = 1000)
    plt.close(fig = fig)

def draw_features(model, data, desc, plot_count, opt):
    '''
    This function is for model probing. It can be super useful when you need to dig into a model and see
    what really happens.
    data: [time_diff, score, target_intensity]
    '''

    time, event, _ = extract_data(data, opt)                                  # [batch_size, seq_len + 1] & [batch_size, seq_len]
    aggregate_time = torch.cumsum(time[:, 1:], dim = -1).cpu().squeeze()      # [batch_size, seq_len]
    probed_data, timestamp = model.model_prober(data, opt.resolution)
    timestamp = timestamp.detach().cpu().numpy().cumsum()
    event = event.squeeze().cpu().numpy()

    if not os.path.exists(os.path.join(opt.store_dir, 'debug', desc, str(plot_count))):
        os.makedirs(os.path.join(opt.store_dir, 'debug', desc, str(plot_count)))
    
    df_time = pd.DataFrame.from_dict(
            {'Time': aggregate_time, 'Point': np.zeros_like(aggregate_time), 'Event': [f'Event {item}' for item in event]}
    )

    for key, value in probed_data.items():
        value = value.squeeze().detach().cpu().numpy()
        df = pd.DataFrame.from_dict(
                {'Time': timestamp, key: value}
            )

        # Draw plot
        fig = plt.figure()
        sns.lineplot(x = 'Time', y = key, data = df)
        sns.scatterplot(x = 'Time', y = 'Point', data = df_time, palette = 'pastel', hue = 'Event')
        fig.set_size_inches(length,height)

        plt.savefig(os.path.join(opt.store_dir, 'debug', desc, str(plot_count), key + '.png'), dpi = 1000)
        logger.info(f'Debug plot {key} finished drawing.')
        plt.close(fig = fig)
    

def draw(model, data, desc, plot_count, opt):
    if opt.plot_type == 'intensity':
        draw_intensity(model, data, desc, plot_count, opt)
    elif opt.plot_type == 'probability':
        draw_probability(model, data, desc, plot_count, opt)
    elif opt.plot_type == 'debug':
        draw_features(model, data, desc, plot_count, opt)
    else:
        raise Exception('Unknown plot type detected!')
    
'''
True intensity function interpolation functions and their integrals for hawkes process, poisson process, stationary renewal, and self correcting process.
'''

'''
Hawkes process whose intensity function only has one kernel.
'''
def hawkes_1(time, intensity, resolution, device):
    '''
    Hawkes_1 process: \lambda(t) = \mu + a * b * exp(-b(t - t_l))
    In this case, \mu = 0.2, a = 0.8, b = 1, and all past events affect the intensity.

    Args:
    time      : [batch_size, seq_len + 1]
    intensity : [batch_size, seq_len]
              The value of true intensity function.
    resolution: int
    device: conduct all computations on cpu, gpu, or other devices
    '''
    # hyperparameters
    mu = 0.2
    a = 0.8
    b = 1.0

    batch_size = time.shape[0]
    intensity = torch.cat(
        (torch.zeros((batch_size, 1), device = device), intensity[:, :-1]), dim = -1
    )

    time_multiplier = torch.linspace(0, 1, resolution, device = device)
    expand_time = time_multiplier * time[:, 1:].unsqueeze(-1)                  # [batch_size, seq_len, resolution]
    true_intensity = intensity.unsqueeze(-1).repeat(1, 1, resolution) - mu + a * b
                                                                               # [batch_size, seq_len, resolution]
    intensity_multiplier_matrix = torch.exp(-b * expand_time)                  # [batch_size, seq_len, resolution]
    expand_true_intensity = true_intensity * intensity_multiplier_matrix + mu  # [batch_size, seq_len, resolution]
    expand_true_intensity = expand_true_intensity.reshape(batch_size, -1)      # [batch_size, seq_len * resolution]
    expand_true_intensity[:, 0:resolution] = mu
    return expand_true_intensity

def hawkes_1_integral(time, intensity, resolution, device):
    '''
    Hawkes_1 process: \Lambda(t) = \mu * (t - t_l) + a - a * exp(-b(t - t_l)). When t = t_l, \Lambda(t) = 0.
    Hyperparameters that are used here follow what they are in function hawkes_1.

    Args:
    time      : [batch_size, seq_len + 1]
    intensity : [batch_size, seq_len]
              The value of true intensity function.
    resolution: int
    device: conduct all computations on cpu, gpu, or other devices
    '''
    # hyperparameters
    mu = 0.2
    a = 0.8
    b = 1.0
    
    # Integral part 1
    batch_size = time.shape[0]
    time_multiplier = torch.linspace(0, 1, resolution, device = device)
    expand_time = time_multiplier * time[:, 1:].unsqueeze(-1)                  # [batch_size, seq_len, resolution]
    mu_integral = mu * expand_time                                             # [batch_size, seq_len, resolution]
    basic_exponential_integral = a - a * torch.exp(-b * expand_time)           # [batch_size, seq_len, resolution]

    # Integral part 2
    table = torch.diag_embed(time[:, 2:-1], offset = -2)                       # [batch_size, seq_len, seq_len]
    table = torch.cumsum(table, dim = -2)                                      # [batch_size, seq_len, seq_len]
    reversed_cumsum_of_table = torch.cumsum(table.flip(-1), dim = -1).flip(-1) # [batch_size, seq_len, seq_len]
    table_mask = (table != 0).int()                                            # [batch_size, seq_len, seq_len]
    reversed_cumsum_of_table *= table_mask                                     # [batch_size, seq_len, seq_len]
    historical_multiplier = torch.exp(-b * reversed_cumsum_of_table)           # [batch_size, seq_len, seq_len]
    historical_multiplier *= table_mask                                        # [batch_size, seq_len, seq_len]

    historical_integral = basic_exponential_integral.unsqueeze(-1) * historical_multiplier.unsqueeze(-2)
                                                                               # [batch_size, seq_len, resolution, seq_len]
    historical_integral = torch.sum(historical_integral, dim = -1)             # [batch_size, seq_len, resolution]

    # Get the integral
    expand_true_integral = mu_integral + basic_exponential_integral + historical_integral
                                                                               # [batch_size, seq_len, resolution]
    expand_true_integral = expand_true_integral.reshape(batch_size, -1)        # [batch_size, seq_len * resolution]
    expand_true_integral[:, 0:resolution] = mu_integral[:, 0, :]               # [batch_size, seq_len * resolution]

    return expand_true_integral


'''
Hawkes process whose intensity function has multiple kernels.
'''
def hawkes_2(time, intensity, resolution, device):
    '''
    Hawkes_2 process: \lambda(t) = \mu + a_1 * b_1 * exp(-b_1(t - t_l)) + a_2 * b_2 * exp(-b_2(t - t_l))
    In this case, \mu = 0.2, a_1 = 0.4, b_1 = 1, a_2 = 0.4, b_2 = 20.0, and all past events affect the intensity.

    It seems that we have no choice but to solve the intensity iteratively.

    Args:
    time      : [batch_size, seq_len + 1]
    intensity : [batch_size, seq_len]
              The value of true intensity function.
    resolution: int
    device: conduct all computations on cpu, gpu, or other devices
    '''
    # hyperparameters
    mu = 0.2
    a_1 = 0.4
    a_2 = 0.4
    b_1 = 1.0
    b_2 = 20.0

    batch_size, seq_len = time.shape
    seq_len -= 1
    p1d = (1, 0, 0, 0)

    expand_true_intensity = torch.ones((batch_size, seq_len, resolution), device = device) * mu
                                                                               # [batch_size, seq_len, resolution]
    expand_time = (time.unsqueeze(-1) / (resolution - 1)).repeat(1, 1, resolution - 1)
                                                                               # [batch_size, seq_len + 1, resolution - 1]
    expand_time = torch.nn.functional.pad(expand_time, p1d)                    # [batch_size, seq_len + 1, resolution]

    time_cumsum = torch.cumsum(expand_time.reshape(batch_size, -1), dim = -1)  # [batch_size, (seq_len + 1) * resolution]
    time_cumsum = time_cumsum.reshape(batch_size, seq_len + 1, resolution)     # [batch_size, (seq_len + 1), resolution]
    for seq_index in range(2, seq_len + 1):
        expand_batch_time = time_cumsum[:, seq_index:, :] - time_cumsum[:, seq_index, 0]
                                                                               # [batch_size, seq_len - seq_index + 1, resolution]
        expand_intensity_add = a_1 * b_1 * torch.exp(-b_1 * expand_batch_time) + a_2 * b_2 * torch.exp(-b_2 * expand_batch_time)
                                                                               # [batch_size, seq_len - seq_index + 1, resolution]
        p2d = (0, 0, seq_index - 1, 0)
        expand_true_intensity += torch.nn.functional.pad(expand_intensity_add, p2d)
                                                                               # [batch_size, seq_len, resolution]
    
    expand_true_intensity[:, 0, :] = mu
    expand_true_intensity = expand_true_intensity.reshape(batch_size, seq_len * resolution)
                                                                               # [batch_size, seq_len * resolution]
    return expand_true_intensity

def hawkes_2_integral(time, intensity, resolution, device):
    '''
    Hawkes_2 process: \Lambda(t) = \mu * (t - t_l) + a_1 - a_1 * exp(-b_1(t - t_l)) + a_2 - a_2 * exp(-b_2(t - t_l)).
    When t = t_l, \Lambda(t) = 0.
    Hyperparameters that are used here follow what they are in function hawkes_2.

    Args:
    time      : [batch_size, seq_len + 1]
    intensity : [batch_size, seq_len]
              The value of true intensity function.
    resolution: int
    device: conduct all computations on cpu, gpu, or other devices
    '''
    # hyperparameters
    mu = 0.2
    a_1 = 0.4
    a_2 = 0.4
    b_1 = 1.0
    b_2 = 20.0

    # Integral part 1
    batch_size = time.shape[0]
    time_multiplier = torch.linspace(0, 1, resolution, device = device)
    expand_time = time_multiplier * time[:, 1:].unsqueeze(-1)                  # [batch_size, seq_len, resolution]
    mu_integral = mu * expand_time                                             # [batch_size, seq_len, resolution]
    basic_exponential_integral_1 = a_1 - a_1 * torch.exp(-b_1 * expand_time)   # [batch_size, seq_len, resolution]
    basic_exponential_integral_2 = a_2 - a_2 * torch.exp(-b_2 * expand_time)   # [batch_size, seq_len, resolution]
    basic_exponential_integral = basic_exponential_integral_1 + basic_exponential_integral_2
                                                                               # [batch_size, seq_len, resolution]

    # Integral part 2
    table = torch.diag_embed(time[:, 2:-1], offset = -2)                       # [batch_size, seq_len, seq_len]
    table = torch.cumsum(table, dim = -2)                                      # [batch_size, seq_len, seq_len]
    reversed_cumsum_of_table = torch.cumsum(table.flip(-1), dim = -1).flip(-1) # [batch_size, seq_len, seq_len]
    table_mask = (table != 0).int()                                            # [batch_size, seq_len, seq_len]
    reversed_cumsum_of_table *= table_mask                                     # [batch_size, seq_len, seq_len]
    historical_multiplier_1 = torch.exp(-b_1 * reversed_cumsum_of_table)       # [batch_size, seq_len, seq_len]
    historical_multiplier_1 *= table_mask                                      # [batch_size, seq_len, seq_len]
    historical_multiplier_2 = torch.exp(-b_2 * reversed_cumsum_of_table)       # [batch_size, seq_len, seq_len]
    historical_multiplier_2 *= table_mask                                      # [batch_size, seq_len, seq_len]

    historical_integral_1 = basic_exponential_integral_1.unsqueeze(-1) * historical_multiplier_1.unsqueeze(-2)
                                                                               # [batch_size, seq_len, resolution, seq_len]
    historical_integral_2 = basic_exponential_integral_2.unsqueeze(-1) * historical_multiplier_2.unsqueeze(-2)
                                                                               # [batch_size, seq_len, resolution, seq_len]
    historical_integral = torch.sum(historical_integral_1, dim = -1) + torch.sum(historical_integral_2, dim = -1)
                                                                               # [batch_size, seq_len, resolution]

    # Get the integral
    expand_true_integral = mu_integral + basic_exponential_integral + historical_integral
                                                                               # [batch_size, seq_len, resolution]
    expand_true_integral = expand_true_integral.reshape(batch_size, -1)        # [batch_size, seq_len * resolution]
    expand_true_integral[:, 0:resolution] = mu_integral[:, 0, :]               # [batch_size, seq_len * resolution]

    return expand_true_integral

'''
Time-independent poisson process
'''
def poisson(time, intensity, resolution, device):
    '''
    Poisson process: \lambda(t) = 1
    The intensity function of poisson process is a constant.

    Args:
    time       : [batch_size, seq_len + 1]  (not used in this function)
    intensity  : [batch_size, seq_len]
               The value of true intensity function.
    resolution : int
    device: conduct all computations on cpu, gpu, or other devices
    '''
    # hyperparameters
    lam = 1

    batch_size, seq_len = intensity.shape
    return torch.ones((batch_size, seq_len * resolution), device = device) * lam
                                                                               # [batch_size, seq_len * resolution]

def poisson_integral(time, intensity, resolution, device):
    '''
    Poisson process: \lambda(t) = 1 and \Lambda(t) = t (\Lambda(t) is the integral of \lambda(t))

    Args:
    time       : [batch_size, seq_len + 1]  (not used in this function)
    intensity  : [batch_size, seq_len]
               The value of true intensity function.
    resolution : int
    device: conduct all computations on cpu, gpu, or other devices
    '''
    # hyperparameters
    lam = 1

    batch_size, _ = intensity.shape
    time_multiplier = torch.linspace(0, 1, resolution, device = device)
    expand_time = time_multiplier * time[:, 1:].unsqueeze(-1)                  # [batch_size, seq_len, resolution]

    return (expand_time * lam).reshape(batch_size, -1)                         # [batch_size, seq_len * resolution]


'''
Stationary renewal process, whose probability distribution instead of intensity function is defined.
'''
def stationary_renew(time, intensity, resolution, device):
    '''
    The stationary renewal process: \lambda(t) = -0.797885*exp(-0.5*(log(t))**2) / (-t + t * erf(0.707107 * log(t)))
    The intensity function only matches the explicitly given lognorm distribution used in the synthetic data generator. 
    Please check and modify this function if you want to use another hyperparameter set for the stationary renewal process during data generation.

    Timestamp 0 will be shifted to a very small value.

    Args:
    time       : [batch_size, seq_len + 1]
    intensity  : [batch_size, seq_len]
               The value of true intensity function.
    resolution : int
    device: conduct all computations on cpu, gpu, or other devices
    '''

    batch_size, _ = time.shape
    time_multiplier = torch.linspace(0, 1, resolution, device = device)
    expand_time = time_multiplier * time[:, 1:].unsqueeze(-1)                  # [batch_size, seq_len, resolution]
    expand_time[:, :, 0] += 1e-8
    expand_true_intensity = -0.797885*torch.exp(-0.5*(torch.log(expand_time))**2) / (-expand_time + expand_time * torch.erf(0.707107 * torch.log(expand_time)))
                                                                               # [batch_size, seq_len, resolution]
    expand_true_intensity = expand_true_intensity.reshape(batch_size, -1)      # [batch_size, seq_len * resolution]
    return expand_true_intensity

def stationary_renew_probability(time, intensity, resolution, device):
    '''
    We won't implement the integral of stationary renewal's intensity function.
    We will directly use the distribution, instead.

    Args:
    time       : [batch_size, seq_len + 1]
                 The original timestamp sequence.
    intensity  : [batch_size, seq_len]
                 The value of ture intensity function at all event points.
    resolution : int
    device: conduct all computations on cpu, gpu, or other devices
    '''
    # hyperparameter
    s = np.sqrt(1)
    mu = 0

    batch_size = time.shape[0]
    from scipy.stats import lognorm
    time_multiplier = torch.linspace(0, 1, resolution, device = device)        # [resolution]
    expand_time = time_multiplier * time[:, 1:].unsqueeze(-1)                  # [batch_size, seq_len, resolution]
    distribution_values = lognorm.pdf(expand_time.cpu().numpy(), s = s, scale = np.exp(mu))
                                                                               # [batch_size, seq_len, resolution]
    distribution_values = torch.from_numpy(distribution_values).reshape(batch_size, -1)
                                                                               # [batch_size, seq_len * resolution]
    return distribution_values


'''
Self-correct process, which the latest events would drastically decrease the probability of next events in a small time period.
'''
def self_correct(time, intensity, resolution, device):
    '''
    Self correct process has a iterative intensity function. \lambda(t) = exp(mu * tau - alpha * N)
    N is the number of happened events.

    Args:
    time       : [batch_size, seq_len + 1]
    intensity  : [batch_size, seq_len]
               The value of true intensity function when a event happens.
    resolution : int
    device: conduct all computations on cpu, gpu, or other devices
    '''
    # Hyperparameters
    mu = 1
    alpha = 1

    batch_size = time.shape[0]
    time_multiplier = torch.linspace(0, 1, resolution, device = device)
    shift_intensity = torch.cat((torch.ones(batch_size, 1, device = device), intensity[:, :-1]), dim = -1)
                                                                               # [batch_size, seq_len]
    start_intensity = shift_intensity / torch.exp(torch.tensor(alpha))         # [batch_size, seq_len]
    expand_time = time_multiplier * time[:, 1:].unsqueeze(-1)                  # [batch_size, seq_len, resolution]
    start_intensity = start_intensity.unsqueeze(-1).repeat(1, 1, resolution)   # [batch_size, seq_len, resolution]
    expand_intensity = start_intensity * torch.exp(mu * expand_time)           # [batch_size, seq_len, resolution]
    expand_intensity = expand_intensity.reshape(batch_size, -1)                # [batch_size, seq_len * resolution]

    return expand_intensity

def self_correct_integral(time, intensity, resolution, device):
    '''
    self correct process has intensity function: \lambda(t) = exp(mu * tau - alpha * N)
    N is the number of happened events. Omi et al. claim self correct process doesn't aggregate intensity functions of all
    historical events, but it does just like the Hawkes process.

    Args:
    time       : [batch_size, seq_len + 1]
    intensity  : [batch_size, seq_len]
               The value of true intensity function when a event happens.
    resolution : int
    device: conduct all computations on cpu, gpu, or other devices
    '''
    # hyperparameters
    mu = 1
    alpha = 1
    
    time_interval = time[:, 1:]                                                # [batch_size, seq_len]
    batch_size, seq_len = time_interval.shape
    N = torch.arange(0, seq_len, device = device)\
             .repeat(batch_size, 1)\
             .repeat_interleave(resolution, dim = -1)\
             .reshape(batch_size, seq_len, -1)                                 # [batch_size, seq_len, resolution]
    time_multiplier = torch.linspace(0, 1, resolution, device = device)
    expand_time = time_multiplier * time_interval.unsqueeze(-1)                # [batch_size, seq_len, resolution]
    historical_part = torch.exp(mu * time[:, :-1])                             # [batch_size, seq_len]
    historical_part = torch.cumprod(historical_part, dim = -1)                 # [batch_size, seq_len]
    historical_part = historical_part.repeat_interleave(resolution, dim = -1)  # [batch_size, seq_len * resolution]
    historical_part = historical_part.reshape(batch_size, seq_len, resolution) # [batch_size, seq_len, resolution]
    integral = (torch.exp(mu * expand_time - alpha * N) - torch.exp(-alpha * N))/mu * historical_part
                                                                               # [batch_size, seq_len, resolution]
    integral = integral.reshape(batch_size, -1)                                # [batch_size, seq_len * resolution]
    return integral

true_intensity_dict = {
    'hawkes_1': hawkes_1,
    'hawkes_2': hawkes_2,
    'poisson': poisson,
    'stationary_renewal': stationary_renew,
    'self_correct': self_correct,
}

true_probability_dict = {
    'hawkes_1': [hawkes_1, hawkes_1_integral],
    'hawkes_2': [hawkes_2, hawkes_2_integral],
    'poisson': [poisson, poisson_integral],
    'stationary_renewal': [stationary_renew_probability],
    'self_correct': [self_correct, self_correct_integral],
}

def extract_data(data, opt):
    '''
    Why do we need this function?
    Because different dataloaders would give minibatches in quite different manners, and there is no way
    to force all dataloader to comply a pre-defined data output structure. 

    extract_data should choose the proper extract data function stored in dictionary 'extract_data_from_rawdata'
    by the name of used dataloader.
    All functions defined in 'extract_data_from_rawdata' may receive raw data from the dataloader(batch_size is always 1), extract
    time and intensity sequences, and output them.

    Addition: The expected time sequences should have shape [batch_size, seq_len + 1] and the first item of each sequence is 0. Other values in 
    a time sequence should be the time interval between two adjoint events. Several algorithms may require an escape time to guarantee
    all event sequences having the same length on the timeline. But for simplicity, one should remove such escape events here.
    '''
    return extract_data_from_rawdata[opt.dataloader_name](data)

def syn_extract(raw_data):
    [time_seq, event_seq, score, mask, intensity], (mean, var) = raw_data
    return time_seq, event_seq[:, 1:], intensity

def ctlstm_extract(raw_data):
    return raw_data[0][1][:, :-1], raw_data[2]

def cnf_extract(raw_data):
    pass

def ifl_extract(raw_data):
    '''
    Time, event, intensity
    '''
    [event, time, mask], score, (mean, var), intensity = raw_data              # [batch_size, seq_len + 1]
    batch_size = event.shape[0]

    event = event[:, :-1]                                                      # [batch_size, seq_len]
    time = torch.cat(
        (torch.zeros(batch_size, 1, device = event.device), time[:, :-1]), dim = -1
    )                                                                          # [batch_size, seq_len]
    return time, event, intensity

extract_data_from_rawdata = {
    'syn': syn_extract,
    'ctlstm': ctlstm_extract,
    'cnf': cnf_extract,
    'ifl': ifl_extract
}