import matplotlib.pyplot as plt
import seaborn as sns
import os
from src.fakenews.utils import getLogger

logger = getLogger(name = __file__)

'''
This is the main plotter library.
For all tpp models waiting for being evaluated, you should have two methods implemented.
1. function_prober(data, resolution):
Args:
   1. data: The fresh raw data from the corresponding dataloader. Batch size is 1 and can not be changed.
   2. resolution: It elabrates how many additional time points are inserted between two events. In fact, because
                  new time points are generated by torch.linspace(0, 1, resolution) * time, there are only
                  (resolution - 2) new points.
Output:
   If this model is present in list named 'intensity_available', its function_prober() should have three kinds of outputs.
   1. integral: the values of the intensity integral function at all probing points.
   2. intensity: the values of the intensity function at all probing points.
   3. timestamp: cumulative timestamps of all points that have been used during model distribution estimation.
   Otherwise, it should have two kinds of outputs.
   1. probability: the values of the probability distribution at all probing points.
   2. timestamp: cumulative timestamps of all points that have been used during model distribution estimation.
Function behaviours:
This function should return

2. model_prober
'''

def draw(model, minibatch, desc, batch_idx, opt):
    '''
    This function is for model probing. It can be super useful when you need to dig into a model and see
    what really happens.
    data: [time_diff, score, target_intensity]
    '''

    '''
    In the new pipeline, each plot is defined as a instruction list. draw_features() should extract and
    call correct seaborn APIs from each plot dict. The structure of the 'plots dict goes as follows:
    {
        ...
        '[plot name]':
        [
            ...
            {
                'plot_type': '[plot_type]'
                'length': [diagram length],
                'height': [diagram height],
                'kwargs':
                {
                    ...'[arguments sent to seaborn APIs.]'
                }
            }
            ...
        ]
        ...
    }
    '''

    plots = model.plot(minibatch, opt)
    
    # Create the plot storing directory if not exist.
    plot_store_dir_for_this_batch = os.path.join(opt.store_dir, opt.plot_type, desc, str(batch_idx))
    if not os.path.exists(plot_store_dir_for_this_batch):
        os.makedirs(plot_store_dir_for_this_batch)
    
    for plot_name, plot_instructions in plots.items():
        fig = plt.figure()
        for instruction in plot_instructions:
            if instruction.get('length') and instruction.get('height'):
                fig.set_size_inches(instruction.get('length'), instruction.get('height'))
            getattr(sns, instruction['plot_type'])(**instruction['kwargs'])
        
        logger.info(f'{plot_name} for No.{batch_idx} minibatch in {desc} dataset finished drawing!')
        plt.savefig(os.path.join(plot_store_dir_for_this_batch, plot_name + '.png'), dpi = 1000)
        plt.close(fig = fig)


'''
def spearman_and_l1(model, data, opt):
    model_probability, timestamp = expand_model_probability(model, data, opt)  # [batch_size, seq_len * resolution]
    time, event, intensity = extract_data(data, opt)                           # [batch_size, seq_len + 1] & [batch_size, seq_len]
    true_probability = expand_true_probability(time, intensity, opt = opt)     # [batch_size, seq_len * resolution]

    # torch.tensor to numpy.array
    model_probability = model_probability.squeeze().detach().cpu().numpy()
    if np.isnan(model_probability).any():
        \'''
        Model intensity prediction has failed!
        \'''
        logger.error('We detect NaN in the intensity predictions! Please try again after checking the training log and retraining your model.')
        return 0

    timestamp = timestamp.detach().cpu().numpy().cumsum()
    event = event.squeeze().cpu().numpy()

    rho, r, L1 = 0, 0, 0
    if true_probability is not None:
        true_probability = true_probability.squeeze().detach().cpu().numpy()
        # Calculate pearson, spearman corrilation and L^1 distance here.
        # Then, print these values directly on the plots.
        
        # Spearman correlation
        rho = spearmanr(a = true_probability, b = model_probability)[0]
        # Pearson correlation
        r = np.corrcoef(x = true_probability, y = model_probability)[0, 1]
        # L1 distance
        L1 = L1_distance(x = true_probability, y = model_probability, timestamp = timestamp, resolution = opt.resolution)
        # KL-divergence
        
    
    return rho, r, L1

'''